// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dotnet_backend_freshmart.Data;

#nullable disable

namespace dotnet_backend_freshmart.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916131500_AddPurchaseOrderEntities")]
    partial class AddPurchaseOrderEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "employee_role", new[] { "cashier", "store_manager", "warehouse_staff", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "loyalty_tier", new[] { "deal", "silver", "gold", "diamond" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "order_status", new[] { "pending", "completed", "cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "cash", "viet_qr", "pos_card" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "shift_status", new[] { "active", "closed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("customer_code_seq");
            modelBuilder.HasSequence<int>("employee_code_seq");
            modelBuilder.HasSequence<int>("order_code_seq");
            modelBuilder.HasSequence<int>("supplier_code_seq");
            modelBuilder.HasSequence<int>("purchase_order_code_seq");
#pragma warning restore 612, 618
        }
    }
}
